spring:
  datasource:
    url: jdbc:mysql://localhost:3306/car_rental_test?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true