spring:
  datasource:
    url: jdbc:h2:mem:file:~/h2/app_db;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
